receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4319"

processors:
  batch:

exporters:
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
